### ISSUE TITLE
Better handling of servo commits

### ISSUE THREAD

**Issue by indygreg** [glandium/pulsebot#13]
Pulsebot didn't take kindly to https://hg.mozilla.org/integration/autoland/pushloghtml?changeset=be030db91f007f59dcbd4b51033caee8b2251a8f and started posting to 5 digit bugs.

Pulsebot should be made to handle servo commits better.

For the time being, servo commits can be identified by a prefix of `servo: ` in the commit message summary line.

**Comment by glandium** [comment]
Fixed in f933741d0076fce630f858b8cd27f96fa3585f78
