### ISSUE TITLE
pulsebot shouldn't change bug status from VERIFIED to RESOLVED

### ISSUE THREAD

**Issue by globau** [glandium/pulsebot#18]
when a bug is in the VERIFIED state it's at its final status.

if a repo is touched that results in an old bug being merged, pulsebot incorrectly changes the bug from VERIFIED to RESOLVED, which in turn updates the `last_resolved` field on the bug.  this change throws out a lot of metric gathering.

eg.  https://bugzilla.mozilla.org/show_bug.cgi?id=400893#c13
Status: VERIFIED → RESOLVED
Last Resolved: 10 years ago → 12 hours ago

pulsebot shouldn't update the bug's status to RESOLVED if it's currently VERIFIED.

**Comment by glandium** [comment]
Same for status CLOSED, I guess.
