### ISSUE TITLE
Add "first-build-with" information when patch lands

### ISSUE THREAD

**Issue by squelart** [glandium/pulsebot#30]
Spawned from https://bugzilla.mozilla.org/show_bug.cgi?id=1651631#c0 :
When a patch lands in mozilla-central, a bugzilla comment is added, which looks like:

    https://hg.mozilla.org/mozilla-central/rev/11541de3ca98
    Status: NEW → RESOLVED
    Closed: 2020-07-09 07:54 AEST
    status-firefox80: affected → fixed
    Resolution: --- → FIXED
    Target Milestone: --- → mozilla80

I think it would be really helpful if that comment also contained the corresponding "build id" in Nightly. For example to tell users when some feature/fix will be available, to more easily correlate crash reports with patches, etc.

Since this comment is currently added as soon as the patch lands in central, I'm guessing we would only know the "last build id without this patch".
Alternatively, this comment could be delayed, or there could be a separate comment later on, in order to show the more useful "first build id with this patch".

Another non-BMO alternative would be a simple service that could link bug numbers and build ids; IIRC there might already be such things, but I can never remember how to find them in the rare times I need them! [Hint from :glob, it's available on the https://hg.mozilla.org/mozilla-central/rev/11541de3ca98 page!]
Having build ids directly in the relevant bug, and be searchable, would be most helpful.

Bonus: Add later comments when the same patch moves to a Beta build id, and then to a Release build id.

**Comment by glandium** [comment]
Pulsebot is not responsible for these messages.
